# Generated by Django 4.0.6 on 2022-08-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guvenlik_Tedbirleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tum_tedbirler', models.TextField(blank=True, max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Hukuksal_Dayanak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hukuksal_dayanak', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Islenen_Veriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islenen_tum_veriler', models.TextField(blank=True, max_length=1000)),
                ('islenen_kisisel_veriler', models.TextField(blank=True, max_length=1000)),
                ('islenen_ozel_nitelikli_veriler', models.TextField(blank=True, max_length=1000)),
                ('gerekli_olmayan_veriler', models.TextField(blank=True, max_length=500)),
                ('amac', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Kayitli_alicilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alicilar', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kayitli_guv_onl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tedbir', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kayitli_işlen_amac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amaclar', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kayitli_kisisel_veriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kisisel_veriler', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kayitli_org_isim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kayitli_org_yetkili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yetkili', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kayitli_ozel_veriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozel_kisisel_veriler', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kayitli_top_yontem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yontemler', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kayitli_tum_veriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kisisel_tum_veriler', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organizasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departman_ismi', models.CharField(blank=True, max_length=70)),
                ('yetkili', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Saklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saklanilan_sure', models.CharField(blank=True, max_length=15)),
                ('saklanilan_yer', models.TextField(blank=True, max_length=100)),
                ('verilere_erişebilen_kisiler', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Surec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sureci', models.TextField(blank=True, max_length=100)),
                ('veri_isleme_faaliyeti', models.TextField(blank=True, max_length=200)),
                ('kisisel_verisi_islenen_kisi', models.CharField(blank=True, max_length=40)),
                ('kisisel_verinin_toplanma_yontemi', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tum_Envanter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departman_ismi', models.CharField(blank=True, max_length=70)),
                ('yetkili', models.CharField(blank=True, max_length=30)),
                ('is_sureci', models.TextField(blank=True, max_length=100)),
                ('veri_isleme_faaliyeti', models.TextField(blank=True, max_length=200)),
                ('kisisel_verisi_islenen_kisi', models.CharField(blank=True, max_length=40)),
                ('kisisel_verinin_toplanma_yontemi', models.CharField(blank=True, max_length=100)),
                ('islenen_tum_veriler', models.TextField(blank=True, max_length=1000)),
                ('islenen_kisisel_veriler', models.TextField(blank=True, max_length=1000)),
                ('islenen_ozel_nitelikli_veriler', models.TextField(blank=True, max_length=1000)),
                ('gerekli_olmayan_veriler', models.TextField(blank=True, max_length=500)),
                ('amac', models.TextField(blank=True, max_length=1000)),
                ('alici_gruplari_ic', models.TextField(blank=True, max_length=200)),
                ('paylasim_amaci', models.TextField(blank=True, max_length=200)),
                ('alici_gruplari_dis', models.TextField(blank=True, max_length=200)),
                ('paylasilan_veriler', models.TextField(blank=True, max_length=200)),
                ('paylasilan_ulkeler', models.TextField(blank=True, max_length=100)),
                ('paylasim_amaclari', models.TextField(blank=True, max_length=200)),
                ('hukuksal_dayanak', models.TextField(blank=True, max_length=100)),
                ('tum_tedbirler', models.TextField(blank=True, max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='users_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=11)),
                ('kurum_adi', models.CharField(max_length=75)),
                ('email', models.CharField(max_length=30)),
                ('sifre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Yurtdisi_Aktarim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alici_gruplari', models.TextField(blank=True, max_length=200)),
                ('paylasilan_veriler', models.TextField(blank=True, max_length=200)),
                ('paylasilan_ulkeler', models.TextField(blank=True, max_length=100)),
                ('paylasim_amaclari', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Yurtici_Aktarim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alici_gruplari', models.TextField(blank=True, max_length=200)),
                ('paylasim_amaci', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
