# Generated by Django 4.0.6 on 2022-08-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvkk_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('sifre', models.CharField(max_length=30)),
            ],
        ),
    ]
