# Generated by Django 4.0.6 on 2022-08-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvkk_app', '0002_kontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kayili_kisisel_ver_isl_kisiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kisiler', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tum_envanter',
            name='erisebilen_kisiler',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tum_envanter',
            name='islenen_sure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tum_envanter',
            name='saklanilan_yer',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
