# Generated by Django 4.0.6 on 2022-08-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvkk_app', '0003_kayili_kisisel_ver_isl_kisiler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aciklamalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(blank=True, max_length=100)),
                ('aciklama', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
