# Generated by Django 4.0.6 on 2022-08-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvkk_app', '0003_kayitli_kis_ver_isl_kisiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='tum_envanter',
            name='erisen_kisiler',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tum_envanter',
            name='islenen_sure',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tum_envanter',
            name='saklanilan_yer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
