# Generated by Django 4.0.6 on 2022-08-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvkk_app', '0003_alter_tum_envanter_erisen_kisiler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='yeniEnvanter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departman_ismi', models.CharField(blank=True, max_length=70)),
                ('yetkili', models.CharField(blank=True, max_length=30)),
                ('is_sureci', models.TextField(blank=True, max_length=100)),
                ('veri_isleme_faaliyeti', models.TextField(blank=True, max_length=200)),
                ('kisisel_verisi_islenen_kisi', models.CharField(blank=True, max_length=40)),
                ('kisisel_verinin_toplanma_yontemi', models.CharField(blank=True, max_length=100)),
                ('islenen_tum_veriler', models.TextField(blank=True, max_length=1000)),
                ('islenen_kisisel_veriler', models.TextField(blank=True, max_length=1000)),
                ('islenen_ozel_nitelikli_veriler', models.TextField(blank=True, max_length=1000)),
                ('gerekli_olmayan_veriler', models.TextField(blank=True, max_length=500)),
                ('amac', models.TextField(blank=True, max_length=1000)),
                ('alici_gruplari_ic', models.TextField(blank=True, max_length=200)),
                ('paylasim_amaci', models.TextField(blank=True, max_length=200)),
                ('alici_gruplari_dis', models.TextField(blank=True, max_length=200)),
                ('paylasilan_veriler', models.TextField(blank=True, max_length=200)),
                ('paylasilan_ulkeler', models.TextField(blank=True, max_length=100)),
                ('paylasim_amaclari', models.TextField(blank=True, max_length=200)),
                ('hukuksal_dayanak', models.TextField(blank=True, max_length=100)),
                ('tum_tedbirler', models.TextField(blank=True, max_length=3000)),
                ('islenen_sure', models.CharField(blank=True, max_length=300)),
                ('saklanilan_yer', models.CharField(blank=True, max_length=200)),
                ('erisen_kisiler', models.CharField(blank=True, max_length=200)),
            ],
        ),
        
    ]
