# Generated by Django 4.0.6 on 2022-08-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvkk_app', '0004_yenienvanter_alter_tum_envanter_erisen_kisiler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayitli_kis_ver_isl_kisiler',
            name='kisiler',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
